=== VelocityFibre/QFieldCloud/docker-qgis/schemas/deltafile_01.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://opengis.ch/schemas/deltafile.json",
    "type": "object",
    "title": "Delta File Schema",
    "description": "TODO",
    "additionalProperties": true,
    "required": [
        "version",
        "project",
        "id",
        "deltas",
        "files"
    ],
    "definitions": {
        "delta_method_descr": {
            "type": "object",
            "title": "Delta Method Description",
            "description": "The actual changes to be applied to the feature. If 'geometry' is provided, it completely replaces the old one. If 'attributes' provided, it merges the contents with the already existing feature using https://tools.ietf.org/html/rfc7386",
            "additionalProperties": false,
            "properties": {
                "geometry": {
                    "type": ["string", "null"],
                    "title": "Geometry",
                    "description": "Feature's geometry serialized in WKT. GeoJSON has a number of limitations so it was reconsidered.",
                    "format": "wkt",
                    "examples": [
                        "POINT (30 10)",
                        "LINESTRING (30 10, 10 30, 40 40)",
                        "POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))",
                        "MULTIPOINT ((10 40), (40 30), (20 20), (30 10))"
                    ]
                },
                "attributes": {
                    "type": "object",
                    "title": "Attributes",
                    "description": "Feature's attributes to be changed. The rest of the properties are ignored.",
                    "examples": [
                        {
                            "prop1": "new contents"
                        }
                    ],
                    "additionalProperties": true
                },
                "files_sha256": {
                    "type": "object",
                    "title": "Files",
                    "description": "Attachments files names and HEX SHA256 checksums.",
                    "examples": [
                        {
                            "FILE1.jpg": null
                        },
                        {
                            "FILE2.jpg": "5d5b09f6dcb2d53a5fffc60c4ac0d55fabdf556069d6631545f42aa6e3500f2e"
                        }
                    ],
                    "additionalProperties": true
                },
                "is_snapshot": {
                    "type": "boolean",
                    "title": "Is Snapshot",
                    "description": "If the stored data is a snapshot of the whole feature, or only the modified attributes and geometry."
                }
            }
        }
    },
    "properties": {
        "version": {
            "type": "string",
            "title": "The Deltas File Format Version",
            "description": "Currently the only allowed value is 1.0, but in the future there might be newer minor or major versions.",
            "enum": [
                "1.0"
            ]
        },
        "project": {
            "type": "string",
            "format": "uuid",
            "title": "Project ID",
            "description": "The project ID that is current open on QField.",
            "examples": [
                "bbdc0a1b-ade9-4c3d-ad28-59d8f0347689"
            ]
        },
        "id": {
            "type": "string",
            "title": "Delta File ID",
            "description": "The delta file ID generated on the client to distinguish requests.",
            "format": "uuid",
            "examples": [
                "73544c91-6a55-483c-b0af-944c4846c49f"
            ]
        },
        "deltas": {
            "type": "array",
            "title": "Deltas",
            "description": "A list of the deltas to be applied sent to the server.",
            "additionalItems": true,
            "items": {
                "type": "object",
                "title": "A Single Delta",
                "description": "Describes the changes to be applied to a single feature.",
                "additionalProperties": true,
                "required": [
                    "uuid",
                    "localPk",
                    "sourcePk",
                    "localLayerId",
                    "sourceLayerId",
                    "method"
                ],
                "properties": {
                    "uuid": {
                        "type": "string",
                        "format": "uuid",
                        "title": "Delta ID",
                        "description": "A unique identifier of the delta.",
                        "examples": [
                            "ddc41fa4-3961-4127-80f6-7d3e3f3f985b"
                        ]
                    },
                    "exportId": {
                        "type": "string",
                        "format": "uuid",
                        "title": "Export ID",
                        "description": "A unique identifier of the local data snapshot that the delta was generated from. Each of the export ID is unique for each server export and device. Generated client-side.",
                        "examples": [
                            "f7b5230c-d078-4654-9bcc-1adc1646bb28"
                        ]
                    },
                    "clientId": {
                        "type": "string",
                        "format": "uuid",
                        "title": "Client Export ID",
                        "description": "A unique identifier of the client that has exported the project.",
                        "examples": [
                            "f7b5230c-d078-4654-9bcc-1adc1646bb28"
                        ]
                    },
                    "localPk": {
                        "type": "string",
                        "title": "Local Feature ID",
                        "description": "To be able to unique identify features in the layers, we use the first primary key column, or a column named \"fid\" if no primary keys are set. This is the primary key value in the exported project.",
                        "examples": [
                            "ddc41fa4-3961-4127-80f6-7d3e3f3f985b",
                            "unique_string",
                            "123"
                        ]
                    },
                    "sourcePk": {
                        "type": "string",
                        "title": "Source Feature ID",
                        "description": "To be able to unique identify features in the layers, we use the first primary key column, or a column named \"fid\" if no primary keys are set. This is the primary key value in the original project.",
                        "examples": [
                            "ddc41fa4-3961-4127-80f6-7d3e3f3f985b",
                            "unique_string",
                            "123"
                        ]
                    },
                    "localLayerId": {
                        "type": "string",
                        "title": "Local Layer ID",
                        "description": "The layer ID is the same as in the exported QGIS project file. Each delta file is responsible for a single layer. This is the layer id in the exported project.",
                        "examples": [
                            "e933b5aa-6ccb-416f-83e7-5a2ece85cf1a_LayerName"
                        ]
                    },
                    "localLayerCrs": {
                        "type": "string",
                        "title": "Local Layer CRS",
                        "description": "The layer CRS as on QField device.",
                        "examples": [
                            "EPSG:32635",
                            "PROJCS[\"WGS 84 / UTM zone 35N\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",27],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32635\"]]"
                        ]
                    },
                    "localLayerName": {
                        "type": "string",
                        "title": "Local Layer Name",
                        "description": "The layer name as shown ot the QField User.",
                        "examples": [
                            "trees",
                            "Дървета"
                        ]
                    },
                    "sourceLayerId": {
                        "type": "string",
                        "title": "Source Layer ID",
                        "description": "The layer ID is the same as in the QGIS project file. Each delta file is responsible for a single layer. This is the original layer id.",
                        "examples": [
                            "e933b5aa-6ccb-416f-83e7-5a2ece85cf1a_LayerName"
                        ]
                    },
                    "method": {
                        "type": "string",
                        "title": "Method",
                        "description": "What type of operation to be applied to the feature.\n'create' - creates new feature\n'patch' - modifies certain values in an existing feature\n'delete' - deletes an existing feature",
                        "enum": ["create", "patch", "delete"]
                    },
                    "old": {
                        "$ref": "#/definitions/delta_method_descr"
                    },
                    "new": {
                        "$ref": "#/definitions/delta_method_descr"
                    }
                }
            }
        },
        "files": {
            "type": "array",
            "title": "Files",
            "description": "A list of the files to be uploaded to the server.",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "title": "Filename",
                "description": "Filename with path relative to project root",
                "example": "DCIM/photo1.jpg"
            }
        },
        "clientPks": {
            "type": "object",
            "title": "Local to remote primary keys",
            "description": "Map with the client PK as keys and remote data source PK as values. Used when deleting a newly created feature that was never exported back to the client.",
            "additionalProperties": true,
            "examples": [
                {
                    "86f1179c-0885-410a-916c-8b26bedfcc51__123": "fead14da-9d09-4320-a915-2c898f5ac38a"
                }
            ]
        }
    }
}

=== VelocityFibre/QFieldCloud/docker-app/qfieldcloud/core/tests/testdata/delta/deltas/nonspatial_geom_empty_str.json
{
    "deltas": [
        {
            "uuid": "1270b97d-6a28-49cc-83f3-b827ec574fee",
            "clientId": "cd517e24-a520-4021-8850-e5af70e3a612",
            "exportId": "f70c7286-fcec-4dbe-85b5-63d4735dac47",
            "localPk": "1",
            "sourcePk": "1",
            "localLayerId": "nonspatial_5b9be5d0_6faa_4c14_825d_7889615c842c",
            "sourceLayerId": "nonspatial_5b9be5d0_6faa_4c14_825d_7889615c842c",
            "method": "patch",
            "new": {
                "geometry": "",
                "attributes": {
                    "col1": "new_value"
                }
            },
            "old": {
                "geometry": null,
                "attributes": {
                    "col1": "foo"
                }
            }
        }
    ],
    "files": [],
    "id": "2c98410f-e1b2-45e6-9026-97898bfee730",
    "project": "e02d02cc-af1b-414c-a14c-e2ed5dfee52f",
    "version": "1.0"
}
